version: '3'
services:
  nginx:
    image: nginx:stable
    restart: always
    container_name: gl-nginx
    ports:
      - 80:80
    volumes:
      - /data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /data/nginx/static/html:/usr/local/nginx/html



#  docker run -d --name nginx5 -p 80:80 -v /e/github-clone/mall-1/docker-compose/data/nginx/nginx.conf:/etc/nginx/nginx.conf -v /e/github-clone/mall-1/docker-compose/data/nginx/static/html:/usr/share/nginx/html nginx
